name: Update dependencies

on:
  pull_request:
    paths:
      - '.github/workflows/update-dependencies.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0'  # "At 18:00 on Sunday."

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: wntrblm/nox@2022.11.21
      with:
        python-versions: "3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12-dev"
    - name: "Allow nox to run with python 3.6"
      run: pipx runpip nox install 'virtualenv<20.22.0'
    - name: "Setup bot user"
      run: |
        git config --global user.name "manylinux-bot[bot]"
        git config --global user.email "89297709+manylinux-bot[bot]@users.noreply.github.com"
    # we use this step to grab a Github App auth token, so that lastversion can query GitHub API
    # without rate-limit and PRs get run by GHA.
    - uses: tibdex/github-app-token@v2
      id: generate-token
      if: github.ref == 'refs/heads/main' && github.repository == 'pypa/manylinux'
      with:
        app_id: ${{ secrets.MANYLINUX_BOT_APP_ID }}
        private_key: ${{ secrets.MANYLINUX_BOT_APP_PRIVATE_KEY }}
    - name: "Run update native dependencies"
      run: nox --force-color --error-on-missing-interpreters -s update_native_dependencies
      env:
        GITHUB_API_TOKEN: ${{ steps.generate-token.outputs.token || github.token }}
    - name: "Run update downloaded interpreters"
      run: nox --force-color --error-on-missing-interpreters -s update_interpreters_download
    - name: "Run update python dependencies"
      run: nox --force-color --error-on-missing-interpreters -s update_python_dependencies update_python_tools
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main' && github.repository == 'pypa/manylinux'
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update python dependencies
        title: '[Bot] Update dependencies'
        body: |
          Update the versions of our dependencies.

          PR generated by "Update dependencies" [workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        branch: update-dependencies-pr
        committer: "manylinux-bot[bot] <89297709+manylinux-bot[bot]@users.noreply.github.com>"
        author: "manylinux-bot[bot] <89297709+manylinux-bot[bot]@users.noreply.github.com>"
        token: ${{ steps.generate-token.outputs.token }}
        delete-branch: true
